sopt-makers/sopt-recruiting-frontend

src/App.tsx, src/common/components/Radio/index.tsx, src/common/components/Radio/style.css.ts
**Related Issue :** Closes  #9 
---
- `label` (필수)
```tsx
<Radio label="재학" name="학교" value="재학" ... />
```
=> [Design] Radio 공통 컴포넌트 생성

.eslintrc.cjs, package.json, yarn.lock
**Related Issue :** Closes  #17 
---
[eslint-import-resolver-typescript](https://www.npmjs.com/package/eslint-import-resolver-typescript) 플러그인 설치하여 import 에러 해결하였습니다!
=> [Fix] eslint-import-resolver-typescript 설치 및 세팅

package.json, src/common/components/Textarea/TextareaHeader/index.tsx, src/common/components/Textarea/TextareaHeader/style.css.ts, src/common/components/Textarea/index.tsx, src/common/components/Textarea/style.css.ts, yarn.lock
**Related Issue :** Closes  #14 
---
- label: react hook form에 등록될 label,
- register: react hook form 등록
- watch: input 값 실시간으로 체크. onChange와 같은 개념
- required: 필수 값인지 아닌지 체크
- errors: react hook form에서 받아오는 error 객체,
- maxCount: 최대 글자 수, // maxLength로 할 경우 maxLength 이후에는 타이핑이 되지 않아 별도의 prop을 하나 만들었습니다.
```tsx
const {
register,
handleSubmit,
watch,
formState: { errors },
} = useForm();
const maxCount = 700; // data로 나중에 받아옴.
return (
<TextareaHeader maxCount={maxCount} required>
{`3. 최근 1년 이내로 머릿속으로만 생각하고 있던 계획을 행동으로 옮겨본 경험이 있나요? 만약 있다면 어떤. 계획이. 었으며, 행동을 통해 어떤 성장을 이루어냈는지에 대해 구체적으로 서술해 주세요. 만약 없다면, 해당 계획을 행동으로 옮기기 위한 액션 플랜을 서술해 주세요.`}
</TextareaHeader>
<Textarea
label="q1"
register={register}
watch={watch}
required
errors={errors}
maxCount={maxCount}
/>
);
```
=> [Design] Textarea 공통 컴포넌트 생성

src/views/ApplyPage/index.tsx
**Related Issue :** Closes #65 
---
미처 제거하지 못하고 merge한 테스트 코드 제거 했습니다!!!!
=> [Chore] Test 코드 제거

src/common/components/Button/index.tsx, src/common/components/Button/style.css.ts, src/views/MainPage/index.tsx
**Related Issue :** Closes #75 
---
Button 텍스트 부분 제외 클릭 안 되는 에러 수정
Link일 때도 테스트 완료
Tag랑 div 위치 바꿔줬습니다~
=> [Fix] Button 텍스트 부분 제외 클릭 안 되는 에러 수정

src/common/components/Select/index.tsx, src/common/components/Select/style.css.ts, src/common/components/Textarea/Label/index.tsx, src/views/ApplyPage/components/DefaultSection/index.tsx
**Related Issue :** Closes #97 
---
=> [Chore] label과 input 연결

src/common/components/Input/InputLine/index.tsx, src/common/components/Radio/index.tsx, src/common/components/Select/index.tsx, src/views/ApplyPage/components/BottomSection/index.tsx, src/views/ApplyPage/components/CommonSection/index.tsx, src/views/ApplyPage/components/DefaultSection/index.tsx, src/views/ApplyPage/components/PartSection/index.tsx, src/views/ApplyPage/index.tsx, src/views/ApplyPage/types.ts
**Related Issue :** Closes #117 
---
임시저장 구현 다했어요
다른 건 전에 붙였던 것들이랑 비슷하고 코드 보면 이해할 수 있으실 거예요
파트 선택하는 select box에서 파트를 선택하면 해당 파트 질문에 대한 답변들의 register가 등록돼요
근데 만약 다른 파트를 선택하면 해당 파트 질문에 대한 답변들의 register도 등록됩니다
근데 여기서 문제는 기존 파트의 register가 그대로 남아있다는 거예요
그래서 파트를 2개 선택하면 파트질문의 답변이 2배가 되는 문제가 발생했습니다
그래서 `react-hook-form`의 `unregister`를 이용해서 `selectPart` 바뀔 때 마다 기존 `register` 없애주려 했으나 해당 part 질문에 대한 답변만 `unregister` 해주기가 어렵더라고요
왜냐면 label을 질문의 Id 값을 이용해서(ex.`파트${id}질문`) 설정해 줬는데 이를 `unregister` 하기 위해선 해당 Id값이 필요했거든요
이를 구하는 것이 쉽지 않았습니다
<details>
<summary>왜 label에 id 값을 집어넣어줬는가?</summary>
서버에 데이터를 보낼 때 두 개의 값을 보냅니다. 하나는 `질문에 대한 답변`이고 하나는 `질문의 id`예요
이때 이 id 값을 받아오는 게 까다로워서 label에 집어 넣어주고, `getValue` 할 때 id 값을 추출하는 방식을 택했습니다 :)
</details>
그래서 방법을 변경하여
애초에 임시저장 데이터를 받을 때, common 질문에 대한 id , part에 대한 id …
=> [Feat] common, part section 임시 저장 구현

package.json, src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx, src/views/ReviewPage/style.css.ts, yarn.lock
**Related Issue :** Closes #132 
---
=> [Build] 빌드 에러 잡기

src/views/ApplyPage/index.tsx
**Related Issue :** Closes #157 
---
=> [Fix] apply 외의 페이지에서 새로고침 경고창 뜨는 에러 해결

src/views/PasswordPage/index.tsx
**Related Issue :** Closes #160 
---
register name을 잘못 전달하고 있었습니다
=> [Fix] 비번 변경 안되는 에러 해결

src/common/components/Select/index.tsx, src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx, src/views/ApplyPage/components/DefaultSection/index.tsx, src/views/ApplyPage/index.tsx, src/views/ApplyPage/types.ts, src/views/SignedInPage/index.tsx
**Related Issue :** Closes #162 
---
=> [Fix] apply page에 뜨는 에러들 해결

src/views/ApplyPage/components/BottomSection/index.tsx
**Related Issue :** Closes #167 
---
=> [HotFix] 지원서 페이지에서 체크마크 체크 안되는 에러 해결

src/App.tsx, src/common/components/Input/InputLine/utils/validateBirthdate.ts, src/common/components/Layout/Header/index.tsx, src/common/components/Textarea/Input/index.tsx, src/common/constants/validationCheck.ts, src/common/hooks/useDate.tsx, src/styles/reset.css.ts, src/views/ApplyPage/components/ApplyInfo/index.tsx, src/views/ApplyPage/components/FileInput/index.tsx, src/views/ApplyPage/constant.ts, src/views/ApplyPage/index.tsx, src/views/ErrorPage/components/NoMore/index.tsx, src/views/MainPage/index.tsx, src/views/MyPage/index.tsx, src/views/PasswordPage/index.tsx, src/views/ResultPage/components/ScreeningResult.tsx, src/views/ResultPage/index.tsx, src/views/SignInPage/style.css.ts, src/views/SignupPage/index.tsx, src/views/dialogs/SessionExpiredDialog/index.tsx
**Related Issue :** Closes #172 
---
=> [Fix] 3차 QA

src/common/hooks/useDate.tsx
**Related Issue :** Closes #175 
---
=> [Fix] 지원서 확인 기간 늘리기

src/views/ApplyPage/components/ApplyInfo/index.tsx
**Related Issue :** Closes #182 
---
=> [HotFix] 지원서 날짜 수정

src/views/PasswordPage/components/PasswordForm/index.tsx, src/views/PasswordPage/hooks/useMutateChangePassword.tsx, src/views/dialogs/CompleteDialog/index.tsx
**Related Issue :** Closes #195 
---
=> [Feat] 비밀번호 재설정 완료 dialog 붙이기

src/views/ApplyPage/index.tsx
**Related Issue :** Closes #198 
---
=> [Fix] 폼 완료 안 했는데 제출되는 에러 해결

src/views/ApplyPage/components/FileInput/index.tsx
**Related Issue :** Closes #199 
---
=> [Fix] 파일 + 버튼 클릭 시 아무런 액션 발생 안 하는 에러 해결

src/views/ApplyPage/components/CommonSection/index.tsx, src/views/ApplyPage/components/FileInput/index.tsx, src/views/ApplyPage/components/PartSection/index.tsx
**Related Issue :** Closes #203 
---
textarea에 아무런 입력값 없을 때
파일 첨부 시 `파일 추가` 라는 텍스트가 자동으로 추가되도록 구현했어요
만약 파일 삭제하면 해당 텍스트도 제거되도록 했고요
만약 지원자가 그 외의 값을 입력했을 경우 `파일 추가` 라는 텍스트를 채우지도 않고
파일을 제거했을 때도 기존 입력값을 제거하지 않도록 구현했습니다
이를 위해 아래와 같이 현재 입력된 값을 비교해서 조건부로 처리해줬어요
<details>
<summary>코드 보기</summary>
```tsx
uploadTask.snapshot.ref.getDownloadURL().then((url) => {
// ...
getValues(`${section}${id}`) === '' && setValue(`${section}${id}`, '파일 제출');
clearErrors(`${section}${id}`);
});
```
```tsx
const handleClickIcon = () => {
if (inputRef.current) {
if (file) {
// ...
getValues(`${section}${id}`) === '파일 제출' && setValue(`${section}${id}`, '');
} else if (uploadPercent !== -2 && defaultFileName) {
// ...
getValues(`${section}${id}`) === '파일 제출' && setValue(`${section}${id}`, '');
} 
// ...
}
};
``` …
=> [Feat] file 첨부 시 required 처리 하기

src/views/dialogs/SubmitDialog/style.css.ts
**Related Issue :** Closes #98 
---
위의 사진과 같이 에러 처리 해줬습니다~
(파일 input elipsis는 다른 pr에서 처리했어여)
=> [Fix] input 값들 max length 테스트 해보기

src/views/ApplyPage/components/FileInput/index.tsx, src/views/CompletePage/index.tsx
**Related Issue :** Closes #212 
---
apply  |  파일 추가 버튼 클릭 | click-apply-add_file${id}
-- | -- | --
  |   파일 삭제 버튼 클릭 | click-apply-remove_file${id}
  |   파일 추가 완료 | done-apply-add_file${id}
complete |  마이페이지로이동 버튼 클릭 | click-complete-my
액션-페이지-기능 순으로 작성했어요 :)
=> [Feat] amplitude 추적하는 버튼 추가

src/common/components/Layout/components/Header/style.css.ts, src/common/components/Select/style.css.ts, src/common/constants/zIndex.ts, src/views/ApplyPage/components/ApplyCategory/style.css.ts, src/views/ApplyPage/components/ApplyHeader/style.css.ts, src/views/ResultPage/components/style.css.ts
**Related Issue :** Closes #221 
---
```tsx
export const Z_INDEX = {
gnbHeader: 99,      // GNB header
select: 1,          // select 공통 component
options: 2,         // select의 options
applyCategory: 99,  // apply page category
applyHeader: 99,    // apply page header
resultContent: 2,   // result page 내용물
};
```
=> [Refactor] z-index 통합 관리

src/common/components/Layout/components/Footer/constants.tsx, src/common/components/Layout/components/Header/contants.ts, src/common/components/Layout/components/Header/index.tsx, src/views/ApplyPage/components/ApplyHeader/index.tsx, src/views/ApplyPage/index.tsx, src/views/ErrorPage/components/NoMore/index.tsx, src/views/MainPage/index.tsx, src/views/PasswordPage/index.tsx, src/views/ResultPage/index.tsx, src/views/SignupPage/index.tsx
**Related Issue :** Closes #217 
---
makers 지원 기간인지 아닌지에 따라 GNB와 에러 페이지의 link를 해당 링크로 변경되도록 수정했습니다
=> [Refactor] 하드 코딩 지우기

src/common/type/seasonAndGroup.ts, src/views/PasswordPage/components/PasswordForm/index.tsx, src/views/PasswordPage/index.tsx, src/views/ResultPage/components/FinalResult.tsx, src/views/ResultPage/components/ScreeningResult.tsx, src/views/SignInPage/components/SignInForm/index.tsx, src/views/SignInPage/components/SignInInfo/index.tsx, src/views/SignInPage/index.tsx, src/views/SignupPage/components/SignupForm/index.tsx, src/views/SignupPage/index.tsx
**Related Issue :** Closes #232 
---
context를 이용해서 충분히 전달할 수 있는 걸
props로 전달하고 있더라고요
다 context 이용해서 넘겨주는 방식으로 수정해줬어요~
=> [Refactor] 불필요한 props drilling 제거

src/common/type/seasonAndGroup.ts, src/views/PasswordPage/components/PasswordForm/index.tsx, src/views/PasswordPage/index.tsx, src/views/ResultPage/components/FinalResult.tsx, src/views/ResultPage/components/ScreeningResult.tsx, src/views/SignInPage/components/SignInForm/index.tsx, src/views/SignInPage/components/SignInInfo/index.tsx, src/views/SignInPage/index.tsx, src/views/SignupPage/components/SignupForm/index.tsx, src/views/SignupPage/index.tsx
Reverts sopt-makers/sopt-recruiting-frontend#233
실수로 main에 merge 해버렸습니다ㅜㅜ
=> [Revert] 불필요한 props drilling 제거 revert 하기

README.md, src/views/ApplyPage/components/ApplyInfo/index.tsx, src/views/ApplyPage/components/LinkInput/index.tsx, src/views/ErrorPage/components/NoMore/index.tsx, src/views/ErrorPage/index.tsx, src/views/ResultPage/components/ScreeningResult.tsx, src/views/email/auth.html, src/views/email/complete.html
**Related Issue :** Closes #238 
---
`_self`는 불편해서 `_blank`로 수정했어요
`noreferrer`도 추가했습니다
=> [Chore] target blank 설정

src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
**Related Issue :** Closes #244 
---
state를 이용해서 관리해주고 있었는데
확실하게 value를 set 해주기 위해 setValue를 이용하도록 수정해줬어요
=> [Fix] 거주지 임시저장 안 되는 에러 해결

src/common/components/Layout/components/Header/index.tsx, src/common/components/Select/index.tsx, src/views/ApplyPage/components/ApplyInfo/index.tsx
**Related Issue :** Closes #236 
---
GNB 전
https://github.com/user-attachments/assets/f4a6a610-8b0f-41ae-a77d-993a7222a1f3
GNB 수정 후
https://github.com/user-attachments/assets/0b7c9437-f762-4bb4-92f9-4b0d5fbbbb12
select 전
https://github.com/user-attachments/assets/842c2734-3710-4a73-9016-df5cb0cda44d
select 수정 후
https://github.com/user-attachments/assets/8d2b59a4-6075-4965-932b-ebf7703235c1
name 데이터가 업데이트 되기까지 시간이 필요해서 발생한 이슈였어요
name이 도착하면 그때 다같이 렌더링 되도록 수정했어요
코드가 조금 반복되지만 크게 상관 없는 거 같습니다~
<details>
<summary>코드 보기</summary>
```tsx
<ul className={menuList}>
{!isSignedIn && (
<>
{menuItems.map(({ text, path, target, amplitudeId }) => (
<MenuItem key={text} text={text} path={path} target={target} amplitudeId={amplitudeId} />
))}
<MenuItem key="로그인" text="로그인" path="/" …
```
=> [Fix] UI 깜빡깜빡 이슈 해결

index.html
---
일단 GA 붙여습니다~
별 다른 액션은 안 취했고 추후에 필요하면 tag 등 붙일게여
어차피 저희 사이트만 해당 GA tag id 사용할 수 있어서 환경 변수 처리는 하지 않았어요~
=> [Feat] GA 붙이기

src/common/components/Input/components/InputLine/style.css.ts
**Related Issue :** Closes #263 
---
해당 이슈 막기
pointerEvents: 'none' 을 줘서 마우스 클릭 이벤트 차단해줬어여
=> [Fix] 인증번호 전송 안 했는데 에러 메세지 뜨는 에러 해결

src/views/email/complete.html
**Related Issue :** Closes #278 
---
인증코드 메일에서 했던 작업을 지원완료 이메일에도 적용해주었어요 
- PC
- mobile
=> [Feat] 지원완료 이메일 템플릿 수정 및 반응형 추가

src/App.tsx
**Related Issue :** Closes #284 
---
알럿 띄우고, redirect 시킵니다 
https://github.com/user-attachments/assets/fb835ca0-2e59-4e1c-a811-8da40707522b
=> [Feat] 모바일 접속 미지원

src/common/components/Textarea/components/Label/style.css.ts
**Related Issue :** Closes #283 
---
=> [Fix] required dot 멀리 떨어지는 에러 해결

src/common/components/Layout/components/Header/style.css.ts, src/common/components/Layout/style.css.ts
**Related Issue :** Closes #295 
---
min width 수정해주고
GNB 양 옆 padding 수정해줬어요
=> [Fix] min width 수정

src/common/components/Input/components/InputTheme/index.tsx
=> [Fix] 사파리 - 이메일 인증 보낼 시 input 너비 증가되는 에러 해결

src/views/ApplyPage/components/Info/index.tsx
**Related Issue :** Closes #312 
---
=> [Fix] 지원서 페이지 500 에러 해결

src/views/ResultPage/components/ScreeningResult.tsx
**Related Issue :** Closes #272 
---
=> [Chore] 서류 합격 페이지에 들어갈 구글폼 링크 env 처리

src/views/ApplyPage/components/BottomSection/index.tsx
**Related Issue :** Closes #322 
---
=> [Chore] 문구 수정

src/views/ApplyPage/components/BottomSection/index.tsx, src/views/ApplyPage/constant.ts
**Related Issue :** Closes #324 
---
=> [Chore] 문구 재수정

src/App.tsx
**Related Issue :** Closes #326 
---
useEffect로 감싸줘서 최초 마운트 시에 한번만 알럿 받도록 수정했습니다!
그 한번에 어차피 유저는 리크루팅 페이지로 빠져나갈테니까요 !
=> [Fix] 모바일 알럿 코드 useEffect로 감싸주기

src/common/components/Input/components/InputTheme/index.tsx, src/common/components/Input/hooks/useMutateCheckCode.tsx
**Related Issue :** Closes #328 
---
해당 이슈를 재현하기 어려워
일단 어찌댓든 인증 성공하면 에러 메세지 없애는 방향으로 진행해 보았습니다
=> [Fix] 이메일 인증 오류

src/common/components/Layout/components/Header/MenuItem/index.tsx, src/common/components/Layout/components/Header/index.tsx
**Related Issue :** Closes #336 
---
session replay에서 GNB부분에 이름이 보이길래 마스킹 처리해줬어요
=> [Chore] GNB 이름 마스킹 처리

src/views/ResultPage/components/FinalResult.tsx, src/views/ResultPage/components/ScreeningResult.tsx
**Related Issue :** Closes #382 
---
&& 연산자 써서 'false' 값이 들어갔네요. 삼항 연산자로 빈문자열로 대체해줬습니다~~
이거 스쿼시 머지하면 develop->main은 PR 안올리고 cli merge 할게요!
=> [Fix] 결과페이지 폼링크 앞에 false 잘못들어가는 이슈

src/views/SignInPage/components/SignInInfo/style.css.ts, src/views/SignupPage/index.tsx, src/views/SignupPage/style.css.ts
**Related Issue :** Closes #379 
---
SignupPage 반응형 작업은 디자인이 따르고 없고 PasswordPage와 동일하게 작업해달라고 하셔서 
전체 레이아웃만 PasswordPage 참고해서 반응형 추가해줬습니다 ! 
https://github.com/user-attachments/assets/b5bef8ff-e651-461a-bfc3-2c619456a727
=> [Design] Mobile ver. - SignupPage 구현

src/common/components/Input/components/InputTheme/index.tsx
**Related Issue :** Closes #398 
---
사용 안 되는 변수명 수정해줬어요!
=> [Fix] build 에러 잡기

src/views/ApplyPage/constant.ts
**Related Issue :** Closes #406 
---
SOPT 커리큘럼 숙지 관련 내용을 추가하였습니다
=> [Fix] 누락되어있는 SOPT ver. ApplyInfo 추가

src/views/ApplyPage/components/PartSection/index.tsx
**Related Issue :** Closes #412 
---
추가 모집 끝나서 다시 원래대로 돌려줬어요
=> [Chore] 파트 제약 제거

src/common/components/Title/style.css.ts
**Related Issue :** Closes #422 
---
데탑, 테블릿
모바일
=> [Fix] main title word break 설정

src/common/components/Input/components/InputLine/index.tsx, src/common/components/Input/components/InputLine/style.css.ts, src/views/CompletePage/components/Survey.tsx
- NPS N회 제출 -> 1회 제출로 수정 
- 사파리 auto zoom 방지를 위해 모바일뷰 input font size 14px -> 16px로 수정
=> [Deploy] NPS, mobile font size 수정 

.github/auto_assign.yml
**Related Issue :** Closes #442 
---
=> [Chore] reviewer에 주용이 추가

.github/auto_assign.yml
리뷰어 수정 했어요
이상 없다면 바로 머지 부탁드려요
main 까지 업데이트 해주시면 감사드리겠습니다
=> fix: 리뷰어 수정

src/views/ApplyPage/index.tsx
=> [Hotfix] 임시저장 파트명 수정

src/common/components/Input/components/InputTheme/index.tsx, src/common/components/Layout/components/Head/index.tsx, src/common/components/Layout/components/Header/Nav/MenuList/index.tsx, src/common/components/Layout/components/Header/index.tsx, src/common/constants/mode.ts, src/common/hooks/useDate.tsx, src/constants/mode.ts, src/contexts/RecruitingInfoProvider.tsx, src/views/ApplyPage/components/ApplyHeader/index.tsx, src/views/ApplyPage/components/ApplyInfo/index.tsx, src/views/ApplyPage/components/BottomSection/index.tsx, src/views/ApplyPage/components/DefaultSection/index.tsx, src/views/ApplyPage/constant.ts, src/views/ApplyPage/index.tsx, src/views/CompletePage/index.tsx, src/views/MyPage/index.tsx, src/views/PasswordPage/index.tsx, src/views/ResultPage/components/FinalResult.tsx, src/views/ResultPage/components/ScreeningResult.tsx, src/views/ResultPage/index.tsx, src/views/ReviewPage/index.tsx, src/views/SignInPage/components/SignInForm/index.tsx, src/views/SignInPage/components/SignInInfo/index.tsx, src/views/SignInPage/index.tsx, src/views/SignupPage/components/SignupForm/index.tsx, src/views/SignupPage/index.tsx, src/views/UnsupportedPage/index.tsx, yarn.lock
=> 37기 모집 전 배포

src/views/ResultPage/components/ScreeningResult.tsx
=> 인터뷰 기간 수정 후 재배포

src/styles/theme.css.ts
=> 37기 메인 컬러 main 반영

src/views/dialogs/SubmitDialog/index.tsx, src/views/dialogs/style.css.ts
=> 버튼 스타일 이슈 해결

src/views/ResultPage/components/FinalResult.tsx, src/views/ResultPage/components/ScreeningResult.tsx
**Related Issue :** Closes  #524 
---
- 37기 YB 서류 합불 문구 업데이트
- 37기 YB 최종 합불 문구 업데이트
- 먼진측에서 더블 체크 완료하면 머지하겠슴다!
=> [Feat] 37기 YB 합불 문구 업데이트
