- tsconfig.json
- vite.config.ts
close #3 
`common` 폴더 속 폴더들은 alias를 `@`로 시작되게 하였습니다. 
`@common/components/~~` 이런 식으로 하면 너무 길어지는 거 같아 `@components` 이런 식으로 `common`을 생략했습니다.
다만 이렇게 되면 `common` 안에 있지 않은 `pages`, `styles`, `views`와 구분이 다소 어려울 것으로 판단이 되어,
`pages`, `styles`, `views`의 alias는 `@`를 제외한 그냥 `pages/~~`, `styles/~~`, `views/~~` 이런 식으로 진행되게 하였습니다.
처음에는 `common`에만 alias 설정하려 했었는데, `pages`에서 `views` 컴포넌트를 사용하는 등 나중에 중첩 길어질 수도 있을 거 같아 하는 김에 다 해줬습니다.
추후에 common 폴더에 apis나 type과 관련된 폴더가 생길 수도 있을 거 같아 일단은 주석 처리 해뒀습니다.
```typescript
"paths": {
// "@apis/*": ["common/apis/*"],
"@assets/*": ["common/assets/*"],
"@components/*": ["common/components/*"],
"@constants/*": ["common/constants/*"],
"@hooks/*": ["common/hooks/*"],
// "@type/*": ["common/type/*"],
"@utils/*": ["common/utils/*"],
"pages/*": ["pages/*"],
"styles/*": …
```
> [Init] path alias 설정

- index.html
- src/common/components/Dialog/index.tsx
- src/common/components/Dialog/style.css.ts
**Related Issue :** Closes  #13 
---
- `children` (필수)
```tsx
const dialog = useRef<HTMLDialogElement>(null);
const handleOpenDialog = () => {
dialog.current?.showModal();
};
return (  
<button onClick={handleOpenDialog}>Open Modal</button>
<Dialog ref={dialog}>
<h1>내용</h1>
<form method="dialog">
<button>Close</button>
</form>
</Dialog>
);
```
1. ref 생성
```tsx
const dialog = useRef<HTMLDialogElement>(null);
```
2. dialog 여는 handler 생성
```tsx
const handleOpenDialog = () => {
dialog.current?.showModal();
};
```
3. trigger 설정
```tsx
<button onClick={handleOpenDialog}>Open Modal</button>
```
4. Dialog와 ref 연결
```tsx
<Dialog ref={dialog}></Dialog>
```
5. 내용 추가
이때, form method="dialog" 태그 속 button이 dialog를 닫는 역할을 함.
```tsx
<Dialog ref={dialog}>
<h1>내용</h1>
<form method="dialog"> …
```
> [Design] Dialog 공통 컴포넌트 생성

- src/common/components/Callout/index.tsx
- src/common/components/Callout/style.css.ts
**Related Issue :** Closes  #11 
---
- `children` (필수)
- `size`: sm(default) | lg
```tsx
<Callout size="sm">
{`마감 시간 이후에는 지원 제출을 받지 않습니다.\n제출하신 서류와 포트폴리오는 반환하지 않습니다.\n서버 오류를 대비해 지원서를 백업해 두시길 바랍니다.`}
</Callout>
<Callout size="sm">
<SomeComponent />
</Callout>
```
아직 icon에 대한 논의가 완료되지 않아 일단 올리고 추후에 디자인 변경되면 수정하도록 하겠습니다.
icon에 색은 따로 theme으로 빼주지 않았는데요. mds icon을 이용할 생각이었어서 뺄 필요가 없을 것이라 판단해서 그랬습니다. 하지만 mds icon을 사용해도 색을 변경해줘야 하더라고요. theme으로 빼줄까 생각도 했지만 여기서 밖에 사용되지 않아서 빼주진 않았습니다.
```ts
<IconAlertCircle
style={{
width: '32px',
minWidth: '32px',
height: '32px',
borderRadius: '50%',
color: `${colors.yellow700}`,
fill: `${colors.yellow200}`,
}}
/>
```
위와 같이 구현했는데 큰 문제는 없는 거 같습니다.
> [Design] Callout 공통 컴포넌트 생성

- src/common/components/Button/index.tsx
- src/common/components/Button/style.css.ts
**Related Issue :** Closes  #12 
---
- `children` (필수)
- `className`
- `buttonStyle`: 'solid' (default) | 'line';
```tsx
<Button buttonStyle="solid">제출하기</Button>
<Button buttonStyle="line">임시저장</Button>
<Button buttonStyle="line" disabled>
이메일 인증
</Button>
<Button className={buttonStyle} buttonStyle="line" disabled>
확인
</Button>
```
```ts
import { style } from '@vanilla-extract/css';
export const buttonStyle = style({
selectors: {
'html &': {
width: '146px',
},
},
});
```
버튼의 크기가 다양해서 이를 sm, md, lg 등의 variants를 주기 보다 className으로 설정할 수 있도록 해주었습니다.
이때, CSS 우선순위에 밀려 className이 적용 안 될 수 있는데 그럴 경우 
```ts
selectors: {
'html &': {
width: '146px',
},
}
```
이런 식의 꼼수를 이용하여 우선순위를 높여주면 됩니다.
---
active 상태에 대한 디자인을 구현하기 위해
외부 박스(div)와 내부 박스(button)으로 구현을 하게 되었습니다.
actvie 될 때도 transition을 주고 싶었으나 그렇게 할 …
> [Design] Button 공통 컴포넌트 생성

- package.json
- src/common/components/Input/constants.ts
- src/common/components/Input/index.tsx
- src/common/components/Input/style.css.ts
- src/common/components/Input/types.ts
- src/pages/ApplyPage.tsx
- src/pages/MainPage.tsx
- src/styles/theme.css.ts
- src/views/MainPage/style.css.ts
- yarn.lock
**Related Issue :** Closes  #15 
---
@eonseok-jeon 
코드리뷰 반영하면서 진행한 작업사이즈가 커서 comment말고 PR에 작성하였습니다.
이전 내용은 토클에 숨겨두었어요
`ApplyPage.tsx` 를 참고해주세요 
<details>
<summary><strong>🟢 최초 PR </strong></summary>
<br/>
```tsx
const { handleSubmit, ...formObject } = useForm<any>({ mode: 'onBlur' });
const textBoxProps1: TextBoxProps = {
label: '타이틀1',
placeholderText: '플레이스 홀더 텍스트',
size: 'lg',
descriptionText: '더 알아보는 텍스트',
descriptionButton: <MoreButton />,
isRequired: true,
// isFixed: true,
errorText: '이러이러한 형식이 잘못됨',
button: <CheckButton />,
// secondary: true,
pattern: /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/i,
maxLength: 5,
formObject,
};
return (
<form onSubmit={handleSubmit(onSubmit)}>
<TextBox {...textBoxProps1} />
```
부연설명이 필요한 친구들만 정리하자면
- `label` : …
> [Feat] Input 공통 컴포넌트 구현

- src/App.tsx
**Related Issue :** Closes #51 
---
light/dark mode에 맞춰 body에 background 넣기
```tsx
const contextValue = {
isLight,
handleChangeMode: (mode: 'light' | 'dark') => {
setIsLight(mode === 'light' ? true : false);
const body = document.body;
const bodyColor = mode === 'light' ? colors.white : colors.gray950; // theme.color.background
body.style.backgroundColor = bodyColor;
},
};
```
body는 theme보다 상위 태그라 theme이 적용되지 않아 mds color를 이용하여 직접 구현해줬습니다.
> [Fix] body에 background 넣기

- src/common/components/Button/index.tsx
- src/common/components/Button/style.css.ts
- src/views/CompletePage/index.tsx
**Related Issue :** Closes #50 
---
Button 공통 컴포넌트를 이용하여 Link를 사용할 수 있게 하기
```tsx
<Button isLink to="/my">버튼</Button>
```
```tsx
interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement | HTMLAnchorElement> {
...생략
to?: To;
isLink?: boolean;
}
const Button = ({
...생략
to,
isLink = false,
}: ButtonProps) => {
const Tag = isLink ? Link : 'button';
return (
<div className={`...생략`}>
<Tag to={to as To} ...생략>
{children}
</Tag>
</div>
);
};
```
prop to가 optional이라 undefined가 올 수 있는데 속성 to에는 undefined가 올 수 없어 To로 형변환 해줬습니다
> [Refactor] Button 공통 컴포넌트를 이용하여 Link를 사용할 수 있게 하기

- src/common/components/Textarea/Label/index.tsx
- src/common/components/Textarea/Label/style.css.ts
---
Textarea에서 required 점이 아래로 내려가는 에러 해결
점의 위치를 absolute로 해줬고, 최대 텍스트에 relative 줬습니다
질문 전체에 relative 주면 right 값을 주기가 애매해 지거든요
질문 전체는 width가 100%인데 질문이 100% 중 어디서 끝날 지 몰라서요
```
~~질문 끝 (700자) .            <- right: 30px
~~~~~~~~~~~~질문 끝 (500자) .  <- right: 5px
```
이런 식으로 말이죠
> [Fix] Textarea에서 required 점이 아래로 내려가는 에러 해결

- src/views/ErrorPage/index.tsx
**Related Issue :** Closes #85 
---
첫 진입시 500 에러가 뜨게 되면 -1을 넘겨줬을 때 이에 해당하는 페이지가 없어서
뒤로 갈 수가 없습니다
따라서 이를 구분 해줬어요
```tsx
const handleGoBack = (code: 404 | 500) => {
const hasPreviousPage = window.history.length > 1;
if (code === 404 || !hasPreviousPage) {
navigate('/');
} else {
navigate(-1);
}
};
<button className={errorButton} onClick={() => handleGoBack(code)}>
{ERROR_MESSAGE[CODE_KEY]?.button}
</button>
```
> [Fix] 500에러 페이지 뒤로가기 navigation

- src/common/components/Input/InputButton/index.tsx
- src/common/components/Input/InputButton/style.css.ts
- src/views/SignupPage/index.tsx
**Related Issue :** Closes #84 
---
```tsx
<Checkbox required label="check1" formObject={formObject}>
```
수정 완료
> [Fix] /sign-up 페이지 오류

- src/common/components/Button/style.css.ts
- src/common/components/Input/InputLine/style.css.ts
- src/common/components/Layout/Header/MenuItem/style.css.ts
- src/common/components/Select/style.css.ts
- src/common/components/Textarea/Input/style.css.ts
- src/views/ApplyPage/components/FileInput/style.css.ts
- src/views/MainPage/index.tsx
- src/views/dialogs/SubmitDialog/index.tsx
- src/views/dialogs/style.css.ts
**Related Issue :** Closes #95 
---
disabled 되었을 때 위의 예시처럼 not-allowed 되도록 수정했습니다
보기 편하시라고 / mainPage에 더미 코드 추가해놨고, 확인 후 지운 뒤 pr merge 하겠습니다
> [Feat] 제출 확인 dialog에서 checkbox 클릭에 따른 버튼 disabled 상태 변화

- src/common/components/Layout/Header/style.css.ts
- src/common/components/Layout/style.css.ts
**Related Issue :** Closes #91 
---
가로 scroll 시 header도 같이 움직이도록 수정
header `position: 'sticky'`로 변경해줬습니다
> [Fix] 헤더 스크롤 안 되는 에러 해결

- src/common/components/Layout/Header/MenuItem/index.tsx
- src/common/components/Layout/Header/contants.ts
- src/common/components/Layout/Header/index.tsx
**Related Issue :** Closes #81 
---
GNB 링크 수정 완료
type 정의가 반복되어서 이를 하나로 통일해서 관리하고 싶긴 한데 어떻게 관리해줘야 할지 모르겠네여ㅜ
그냥 이대로 갈 지,,
```tsx
interface MenuItemProps {
text: string;
path?: string;
target?: '_blank' | '_self';
}
const MenuItem = ({ text, path, target }: MenuItemProps) => {
...
};
```
```ts
type menuItemsTypes = {
text: string;
path?: string;
target?: '_blank' | '_self';
};
export const MENU_ITEMS: menuItemsTypes[] = [
...
];
```
> [Feat] 헤더 네비게이션 링크 연결

- src/views/ApplyPage/index.tsx
**Related Issue :** Closes #119 
---
Firefox
Chrome
Safari
Arc
좀 아쉽습니다ㅜㅜ
기본 경고창 대신 dialog 띄우고 싶었는데
아무리 찾아도 해당 방법을 찾을 수가 없었어요
library 뒤져봐도 찾을 수 없었습니다ㅜ
오히려 그게 불가능하다는 얘기는 많이 볼 수가 있었네여,,
다른 사이트들은 어떻게 되나 참고해봐도 대부분 기본 경고창 띄워주더라고요
(예, code sandbox, postman)
url 변경을 통한 페이지 이동은 잡아내도 GNB 등의 링크 버튼을 이용한 페이지 이동은 또 못 잡더라고요?
근데 이거 잡으려면 `useBlocker`나 `unstable_usePrompt` 써야 하는데 얘네는 또 warning popup이 아닌 prompt가 뜨더라고요
근데 가만 생각해보니 `/apply` 페이지에는 다른 페이지로 이동시킬 수 있는 링크 버튼이 없어서 이에 대한 고려는 안 해줘도 되었습니다
> [Feat] 페이지 이탈 시 dialog 표시

- src/App.tsx
- src/common/components/Input/InputTheme.tsx
- src/common/components/Layout/style.css.ts
- src/common/constants/validationCheck.ts
- src/views/ApplyPage/components/DefaultSection/index.tsx
- src/views/ApplyPage/index.tsx
- src/views/SignInPage/index.tsx
- src/views/SignupPage/index.tsx
**Related Issue :** Closes #129 
---
- [비밀번호 에러 메세지 수정](https://github.com/sopt-makers/sopt-recruiting-frontend/commit/88e2e95954255a522d01a3ac6d1dd9308efc2c46)
- [회원가입 할 때 이미 존재하는 계정일 때 에러 메세지 띄우기](https://github.com/sopt-makers/sopt-recruiting-frontend/commit/39f2dea76e700f215997ca939f6e1b52319760e6)
- [이메일 인증 버튼 다시 누르면 적혀있던 인증 번호 지우기](https://github.com/sopt-makers/sopt-recruiting-frontend/commit/e5613b27cfcc80a80a8f82383cc97809b6d6c552)
- [회원가입 페이지 에러 인풋창에 자동 포커스](https://github.com/sopt-makers/sopt-recruiting-frontend/commit/0a8b833d3372c7247ab2ab1535de544cc8fd102e)
- [회원가입할 때 에러 처리](https://github.com/sopt-makers/sopt-recruiting-frontend/commit/b3f2cab95bcb2d2e1a084e8df00eae5bf4c2be3d)
- [재학, 휴학 default value가 휴학으로 되어있는 에러 해결](https://github.com/sopt-makers/sopt-recruiting-frontend/c …
> [Fix] merge 과정에서 생긴 에러 해결 및 QA

- src/App.tsx
- src/views/ApplyPage/apis.ts
- src/views/ApplyPage/components/ApplyHeader/index.tsx
- src/views/ApplyPage/components/ApplyInfo/index.tsx
- src/views/ApplyPage/components/BottomSection/index.tsx
- src/views/ApplyPage/components/CommonSection/index.tsx
- src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
- src/views/ApplyPage/components/DefaultSection/index.tsx
- src/views/ApplyPage/components/DefaultSection/style.css.ts
- src/views/ApplyPage/components/PartSection/index.tsx
- src/views/ApplyPage/hooks/useMutateSubmit.tsx
- src/views/ApplyPage/index.tsx
- src/views/ApplyPage/types.ts
- src/views/CompletePage/index.tsx
- src/views/MainPage/index.tsx
- src/views/MyPage/index.tsx
- src/views/ReviewPage/index.tsx
- src/views/SignedInPage/apis.ts
- src/views/SignedInPage/hooks/useGetDraft.tsx
- src/views/SignedInPage/index.tsx
**Related Issue :** Closes #152 
---
`/complete` `/my` 로 나눠져있는 걸 `apply` 페이지와 같이 `/` 에서 렌더링 되도록 했어요
다른 페이지로 이동시 state가 초기화 되는데 그럼 데이터를 다시 얻기 위해 api 요청을 보내야 하거든요
불필요한 서버 리소스를 줄이기 위해 한 페이지에 한 번만 api 요청 보내고 이를 여러 군데 재사용 하는 방식을 택했습니다
이를 위해 context나 prop을 이용해줬습니다
`/` 에서 렌더링 되는 컴포넌트는 `SignInPage`, `ApplyPage`, `CompletePage`, `MyPage` 이렇게 총 4개예요
그 중 `ApplyPage`, `CompletePage`, `MyPage`를 `SignedInPage`에서 관리하고,
`SignInPage`와 나머지 3개를 묶은 `SignedInPage`를 `MainPage`에서 관리하고 있어요
`MainPage`에서는 api 요청시 token이 필요 없는 반면 `SignedInPage`는 token이 필요하거든요
그래서 분리해줬습니다
> Feat/#152 after submita[Feat] 제출 완료 후 flow 구현

- README.md
- package.json
- src/App.tsx
- src/common/components/Input/components/InputTheme/index.tsx
- src/common/components/Layout/components/Header/index.tsx
- src/views/ApplyPage/index.tsx
- src/views/ErrorPage/components/NoMore/index.tsx
- src/views/ErrorPage/index.tsx
- src/views/MyPage/index.tsx
- src/views/PasswordPage/components/PasswordForm/index.tsx
- src/views/SignInPage/components/SignInForm/index.tsx
- src/views/SignInPage/components/SignInInfo/index.tsx
- src/views/SignInPage/hooks/useMutateSignIn.tsx
- src/views/SignInPage/types.ts
- src/views/SignedInPage/index.tsx
- src/views/SignupPage/components/SignupForm/index.tsx
- src/views/dialogs/SessionExpiredDialog/index.tsx
- src/views/dialogs/SubmitDialog/index.tsx
- yarn.lock
**Related Issue :** Closes #193 
---
amplitude 공식문서 보면서 적용해 줬습니다
[참고자료](https://amplitude.com/docs/sdks/analytics/browser/browser-sdk-2) 
현재 추적중인 버튼들은 아래와 같아요
event page | 역할 | 설명 | event name 
-- | -- | -- | --
sign-in | go-to-sign-up | 새지원서작성하기 버튼 클릭 | click-signin-signup
  | go-to-password | 비밀번호재설정하기 버튼 클릭 | click-signin-password
  | login | 로그인 버튼 클릭 | click-signin-signin
  |   |   |  
sign-up | send-email | 이메일인증 버튼 클릭 | click-signup-email
  | go-to-apply | 지원서작성하기 버튼 클릭 | click-signup-apply
  |   |   |  
password | send-email | 이메일인증 버튼 클릭 | click-password-email
  | change-password | 비밀번호변경하기 버튼 클릭 | click-password-password
  |   |   |  
apply | draft | 임시저장 버튼 클릭 | click-apply-draft
  | submit | 제출하기 버튼 클릭 | click-apply-submit
  | cancel-submit | 검토하기 버튼 클릭 | click-apply-cancel
  …
> [Feat] amplitude로 사용자 트래킹 하기

- src/views/SignupPage/components/SignupForm/index.tsx
- src/views/SignupPage/hooks/useMutateSignUp.tsx
- src/views/dialogs/ExistingApplicantDialog/index.tsx
**Related Issue :** Closes #204 
---
서버에서 중복된 사용자일 시 400 에러 띄워줍니다
이를 이용해서 400 에러 시 모달창을 띄워줬어요!
> [Feat] 같은 지원자 회원가입 시도 막기

- src/common/components/Layout/components/Header/index.tsx
- src/common/hooks/useDate.tsx
- src/common/store/recruitingInfoContext.ts
- src/views/MainPage/index.tsx
- src/views/ResultPage/components/FinalResult.tsx
- src/views/ResultPage/components/ScreeningResult.tsx
- src/views/ResultPage/index.tsx
- src/views/SignInPage/components/SignInInfo/index.tsx
- src/views/SignInPage/index.tsx
**Related Issue :** Closes #207 
---
soptName을 서버로 부터 받아와서 해당 name에 makers가 포함 되었는지 여부에 따라
makers 모집인지 sopt 모집인지 구분해 줬어요
이를 이용해서 공고 문구, 로고 등을 조건부 렌더링 처리했어요
makers 모집이라면 group 데이터는 렌더링하지 않도록 처리해줬습니다!
useDate()에서는 useGetRecruitingInfo()를 이용해서 데이터를 받아오고 있었어요
근데 useDate를 사용하는 곳에서 한 번 더 useGetRecruitingInfo를 이용해 데이터를 받아오고 있더라고요
그래서 useDate에서 useGetRecruitingInfo data를 사용할 수 있도록 해당 데이터를 넘겨줬습니다
```tsx
const useDate = () => {
const { data, isLoading } = useGetRecruitingInfo();
// ...
return {
...data?.data.season,
};
};
```
> [Refactor] 하드코딩 지우기

- src/common/components/Layout/components/Header/index.tsx
- src/common/hooks/useDate.tsx
- src/common/store/recruitingInfoContext.ts
- src/views/ApplyPage/components/ApplyHeader/index.tsx
- src/views/ApplyPage/index.tsx
- src/views/MainPage/index.tsx
- src/views/MyPage/index.tsx
- src/views/PasswordPage/index.tsx
- src/views/ResultPage/components/FinalResult.tsx
- src/views/ResultPage/components/ScreeningResult.tsx
- src/views/ResultPage/index.tsx
- src/views/SignInPage/components/SignInInfo/index.tsx
- src/views/SignInPage/index.tsx
- src/views/SignupPage/index.tsx
**Related Issue :** Closes #224 
---
전
<br/>
후
- ### latest api 2번 요청 가는 에러 해결
코리 달린 거 확인하고 코드를 다시 보니 api 요청을 두 번씩이나 보내고 있더라고요
한 번만 보낼 수 있도록 수정해줬어요
- ### isMakers -> useDate에서 관리
soptName을 통해 매번 계산 해주고 있던 거를 useDate return 값으로 보내도록 수정했어요
- ### GNB 메이커스 로고 보이기 전 sopt 로고 살짝 보이는 에러 해결
isMakers 판단하기 동안 undefined 상태일 때 sopt 로고가 보이게 되는데 수정해줬습니다
> [Fix] 두 번 api 요청 가는 이슈 해결

- src/views/ResultPage/components/FinalResult.tsx
- src/views/ResultPage/components/ScreeningResult.tsx
**Related Issue :** Closes #216 
---
context를 이용해서 데이터를 가져다 쓰고 있었는데
api data가 들어오지 않은 상태에서 context가 업데이트 되어 값으로 undefined가 뜨게 되었어요
어차피 api data 들어오면 다시 context가 업데이트 되어 정상값으로 바뀌게 되지만
문제는 
서류 결과 확인에서 면접 시간을 알려주기 위해 날짜 계산하는 과정이 있는데
undefined 값이 들어오면 날짜 계산을 못하게 되어 500 에러가 떴었던 겁니다!
따라서 api data 안 들어왔으면 그냥 return 해버리도록 구현했어요
> [Fix] result page 500 에러 해결

- src/views/CompletePage/index.tsx
**Related Issue :** Closes  #228 
---
접수 완료 페이지에도 IsMakers 여부에 따라 텍스트 조건부 렌더링 추가해줬습니다
isMakers 조건부 처리 해주는 곳의 형태를 보니 
```tsx
{season}기 {soptName} {isMakers ? '' : group} 지원하기
```
- FinalResult (최종 합불페이지) 
- ScreeningResult (서류 합불페이지) 
- SignInPage (로그인 페이지) 
```tsx
{seasonS}기 {isMakers ? soptName : group} 지원서
```
- ApplyPage (지원서 작성 페이지) 
이렇게 두가지 형태로 갈리더라구요? 
무슨 기준일까 디자인 피그마도 찾아봤는데 모르겠어서 우선 제가 더 마음에 드는 아래 형태로 고쳐두었습니다! 
문제있다면 말씀해주세요 !!
> [Fix] CompletePage에 isMakers 반영

- src/common/apis/tokenInstance.ts
- src/common/components/Layout/components/Header/index.tsx
- src/views/MainPage/index.tsx
- src/views/SignInPage/components/SignInForm/index.tsx
- src/views/SignInPage/hooks/useMutateSignIn.tsx
- src/views/dialogs/SessionExpiredDialog/index.tsx
**Related Issue :** Closes #230 
---
어떤 페이지든 들어가게 되면 api 요청을 하게 되므로
`interceptors`에서 한 번에 처리해 줬습니다
<details>
<summary>코드 보기</summary>
```tsx
tokenInstance.interceptors.request.use(
(config) => {
const soptApplyAccessToken = localStorage.getItem('soptApplyAccessToken');
const soptApplyAccessTokenExpiredTime = new Date(localStorage.getItem('soptApplyAccessTokenExpiredTime') || '');
const isValidDate = soptApplyAccessTokenExpiredTime.toDateString() !== 'Invalid Date';
const afterRecruiting = isBefore(soptApplyAccessTokenExpiredTime, new Date());
if (!isValidDate || !soptApplyAccessTokenExpiredTime || afterRecruiting) {
localStorage.removeItem('soptApplyAccessToken');
localStorage.removeItem('soptApplyAccessTokenExpiredTime');
window.location.href = '/';
return config;
}
// ...
)
``` …
> [Feat] 토큰 만료 시간 추가

- src/common/constants/validationCheck.ts
- src/views/ApplyPage/components/DefaultSection/index.tsx
- src/views/ApplyPage/components/DefaultSection/style.css.ts
**Related Issue :** Closes  #227 
---
기존엔 3x4 규격이 아닐 시 업로드가 되지 않도록 막았지만, `강제 -> 권장`으로 기능요구조건을 변경함에 따라 관련 코드를 삭제했습니다 
- `object-fit : cover` 처리는 되어있었는데, img 태그의 컨테이너에서 `align-items: center `속성을 주고 있는 것 때문에 object-fit이 제 역할을 안하고 사진이 꽉 채워지지 않고 있더라구요! 그래서 해당 속성도 함께 제거해주었습니다
> [ Fix ] 프로필 사진 규격 제한 제거 

- src/common/components/Checkbox/components/Contentbox/style.css.ts
- src/views/ApplyPage/components/BottomSection/index.tsx
- src/views/ApplyPage/index.tsx
**Related Issue :** Closes  #245 
---
- isMakers에 따라 동아리참석가능여부 텍스트 조건부렌더링 추가 
- ApplyPage의 개인정보 수집 정책 줄바꿈 해결 
1) SOPT Makers의 행사 및 `정기 모임 / 세미나`은 매주 일요일에 진행됩니다.
-> 이거 워딩 기디에게 답장 오는대로 반영할게요! 일단 정기 모임으로 해뒀습니다 
2) ApplyPage의 개인정보 수집 정책 줄바꿈 해결 
이슈에도 코멘트했지만 아래와 같이 줄바꿈이 발생하고 있더라고요 
보니까 letter-spacing의 `%` 단위가 안먹고 있어서 발생한 이슈더라구요 
그래서 figma 개발자도구에서 px값 가져와서 px로 변환시켜주어 해결했습니다
> [Fix] isMakers에 따라 텍스트 조건부 렌더링

- src/views/ErrorPage/components/NoMore/index.tsx
- src/views/ErrorPage/index.tsx
- src/views/ErrorPage/style.css.ts
**Related Issue :** Closes #240 
---
isMakers 여부가 판단이 안되면 header가 뜨지 않아요
이는 로고와 GNB가 동시에 뜨기 위함인데요
에러 페이지에선 api 요청을 하고 있지 않아
새로고침 할 경우 isMakers 여부를 파악할 수가 없어 header가 뜨지 않게 됩니다
이를 위해 헤더 없을 때를 대비해줬어요
<details>
<summary>코드 보기</summary>
```tsx
export const container = styleVariants({
withHeader: [
containerBase,
{
height: calc.subtract('100vh', '74px'),
'@supports': {
'height: (100dvh)': {
height: calc.subtract('100dvh', '74px'),
},
},
},
],
withoutHeader: [
containerBase,
{
height: '100vh',
'@supports': {
'height: (100dvh)': {
height: '100dvh',
},
},
},
],
});
```
</details>
> [Fix] 에러 페이지에서 헤더 없어지는 거 만큼 공백 추가

- src/views/ApplyPage/components/DefaultSection/style.css.ts
**Related Issue :** Closes  #252 
---
object-fit 적용을 위해 align items center를 제거했더니 기본 아이콘 배치가 깨지는 이슈 해결 
align items center 속성은 다시 복구시키되, img 태그 스타일에 `height: 100%`를 추가하여 object fit 적용을 유지시켰습니다!
> [Fix] 프로필 이미지 아이콘 배치 깨짐 해결

- src/App.tsx
- src/views/ApplyPage/components/ApplyHeader/index.tsx
- src/views/ApplyPage/hooks/useMutateSubmit.tsx
- src/views/ApplyPage/index.tsx
- src/views/MyPage/index.tsx
- src/views/ReviewPage/index.tsx
- src/views/SignedInPage/index.tsx
- src/views/dialogs/PreventReviewDialog/index.tsx
**Related Issue :** Closes #234 
---
뒤로 가기가 안 되었던 이유가 같은 페이지 내에서 my component와 review component(-> apply component)를 조건부로 렌더링 하고 있어서 그랬는데요
뒤로 가기 눌렀을 때 다시 my component로 이동하게 하기 위해 새로운 path를 생성해줬습니다
지원서 다시보기 클릭 시 -> `/review`로 이동
지원서 다시보기에서 뒤로가기 클릭 시 -> `/` 로 이동
---
폴더 구조는 아래와 같아요
```
- ApplyPage
ㄴ 여러 컴포넌트들 
- ReviewPage
ㄴ index.tsx -> 이 안에서 ApplyPage의 컴포넌트 재사용
```
`ApplyPage > components > ReviewPage` 로 만들까 하다가
새로운 path라 `views > ReviewPage`로 만들어줬습니다
ApplyPage의 컴포넌트들을 재사용하고 있지만 공통 컴포넌트 까지는 못되므로
따로 폴더 이동 시켜주진 않았어요
이 부분에 대해 다른 의견 있다면 편하게 알려주세여~
---
기존에는 임시저장 api를 이용해서 submit 여부를 파악했는데
submit을 판단하기 위해 많은 데이터를 받아오는 게 리소스가 많이 든다고 판단해서
더 간단한 api인 my page api를 이용해줬어요
---
my page에서 latest api 요청을 한 번 하는데
review page로 이동하면 latest api 요청을 한 번 더 하게 됩니다
my page에서 요청한 데이터를 그대로 이어 받아서 사용하고 싶지만
그럴 경우 …
> [Fix] 지원서 다시보기에서 뒤로가기 안 되는 에러 수정

- src/views/ApplyPage/components/DefaultSection/index.tsx
- src/views/ApplyPage/index.tsx
**Related Issue :** Closes #255 
---
이미지가 10MB 사이즈를 초과해 버리면
setValue('picture', null); 을 이용해서 picture 값은 null이 되는데
실제로 이미지는 image state를 이용해서 보여주고 있기 때문에
이미지가 계속 표시되고 있었어요
기존 image state를 이용해서 10MB 초과 시
setImage('max-size') 로 설정하여
`<img src={image} />` 에서 이미지를 인식 못하도록 하여
이미지가 사라지도록 설정했습니다
그냥 setImage('')로 설정하면
이미지 있는지 없는지 여부를 판단하는 pic || image 
여기에서 판단이 조금 어려워져서 따로 max-size로 처리해줬어요
> [Fix] 사진 에러 메세지 떠도 draft image 안 사라지는 에러 해결

- src/common/components/Textarea/components/Input/index.tsx
- src/common/components/Textarea/components/Input/style.css.ts
- src/common/components/Textarea/index.tsx
**Related Issue :** Closes #260 
---
넉넉하게 100 이하일 때 위와 같은 사이즈가 뜨도록 했어요
세 줄 기준 이 이하의 높이에선 스크롤이 발생해서 딱 스크롤 발생하기 전인 height 112로 설정해줬습니다
> [Fix] 최대글자수에 따라 textArea 높이 동적 설정

- src/views/ApplyPage/components/CommonSection/index.tsx
- src/views/ApplyPage/components/Info/index.tsx
- src/views/ApplyPage/components/Info/style.css.ts
- src/views/ApplyPage/components/PartSection/index.tsx
- src/views/ApplyPage/components/PartSection/style.css.ts
**Related Issue :** Closes #269 
---
디자인은 지원하기 페이지 젤 윗 부분의 지원서 안내 메세지와 동일하게 가져갔어요
서버에서 텍스트를 그대로 받아오기 때문에 강조하는 부분에 대해서는 아직 처리를 못했는데 이건 다음 기수 때 추가해 봐도 좋을 거 같아요
admin 페이지에서 질문 적는 곳에 안내 메세지 작성하고 글자 수 제한을 0으로 설정한 뒤 저장하면 돼요!
> [Feat] 파트 안내 메세지 추가

- src/views/ApplyPage/components/PartSection/index.tsx
- src/views/ApplyPage/types.ts
**Related Issue :** Closes #267 
---
Admin에서 `<플레이스홀더>`로 명시된 placeholder 텍스트를 추출 후 textarea에 주입시켜줍니다 
https://github.com/user-attachments/assets/3f250372-6099-43f4-8831-6d52601679d9
1. question 요소에서 문자열에 `<플레이스홀더>`가 포함되어있는 요소에 한해서
2. `<플레이스홀더>` 구분자를 통해 문자열 분리 후 1번 index 문자열을 추출하고 (구분자 `뒤`에 있는 문자열 추출) 
3. `trim()`을 통해 혹시 모를 앞뒤 공백을 제거해주어 파싱
```tsx
const parsedPlaceholder = question.includes('<플레이스홀더>') && question.split('<플레이스홀더>')[1].trim();
```
4. placeholder 속성 값 분기  
- isFile 일 경우 : 링크로 제출할 경우, 이곳에 작성해주세요. (파일로 제출한 경우에는 ‘파일 제출’이라고 기재 후 제출해주세요.)
- isFile이 아니고, placeholder가 존재할 경우 : placeholder 값 
- isFile이 아니고, placeholder도 undefined일 경우 : 빈문자열
```tsx
placeholder={
isFile
? '링크로 제출할 경우, 이곳에 작성해주세요. (파일로 제출한 경우에는 ‘파일 제출’이라고 기재 후 제출해주세요.)'
: parsedPlaceholder || ''
}
```
> [Feat] admin을 통해 등록된 placeholder 파싱하여 추가

- src/views/ApplyPage/components/CommonSection/index.tsx
**Related Issue :** Closes #276 
---
파트 문항에 적용되어있던 업데이트 사항을 공통 문항에도 적용해요
> [Fix] 공통 문항에 placeholder, optional 적용 

- src/common/components/Textarea/components/Input/index.tsx
- src/common/components/Textarea/index.tsx
- src/views/ApplyPage/components/CommonSection/index.tsx
- src/views/ApplyPage/components/PartSection/index.tsx
**Related Issue :** Closes #288 
---
file input이면 extra input의 props 속성에 defaultFile이 들어가고
url input이면 props 속성에 urls가 들어가는 차이를 가지고 비교를 진행했어요
```tsx
isFileInput={extraInput?.props.defaultFile}
```
> [Feat] FileInput textarea height sm로 만들기

- src/views/ApplyPage/components/CommonSection/index.tsx
**Related Issue :** Closes #299 
---
> [Fix] 공통질문에서 0자 입력 시 textarea 뜨는 에러 해결

- src/common/components/Layout/components/Header/index.tsx
- src/views/CompletePage/index.tsx
- src/views/SignInPage/hooks/useMutateSignIn.tsx
**Related Issue :** 
- Closes #306 
- Closes #301  
---
navigate(0) -> `window.location.reload` 로대체
로그아웃 시 리로드가 안되는 이슈, 
지원서 제출 완료 페이지에서 마이페이지로 이동이 안되는 이슈 
-> 공통점을 찾아보니 모두 `navigate(0)`을 통해 리로드를 시켜주고 있더라구요 
그래서 찾아보니 
[[Bug]: Navigate(0) won't work on Safari](https://github.com/remix-run/react-router/issues/8600#top)
해결되지 않은 위와 같은 이슈가 있더라구요! 
따라서 원인임을 파악하고 `navigate(0)` 사용해주고 있는 모든 코드를 `location.reload()`로 수정해주었습니다
> [Fix] 사파리 - navigate(0) 작동 되지 않는 이슈 해결

- src/common/components/Input/components/Timer/index.tsx
**Related Issue :** Closes #298 
---
다른 페이지를 구경하든 말든 타이머가 작동되기 위해선
현재 시간으로 비교하는 게 좋을 거라고 판단했어요
[아이디어 출처](https://stackoverflow.com/questions/48219925/reactjs-continue-timer-in-the-background)
5시 5분 30초에 인증 전송 버튼을 클릭하면 5시 10분 30초에 마감되도록 말이죠
일단 기존과 동일하게 useEffect를 이용해서 isActive 상태가 되면 타이머가 작동되도록 했어요
false면은 다시 초기화 되고요
```tsx
useEffect(() => {
let timeout: NodeJS.Timeout | null = null;
if (isActive) {
// ...
} else {
setSeconds(INITIAL_TIME - 1);
}
// ...
}, [isActive, onResetTimer]);
```
이때 INITIAL_TIME - 1을 해주는 이유는
예를 들어 5분 `30.001`초에 전송 버튼을 눌렀으면 약 1초의 시간 뒤에 타이머가 4:59로 변하게 되는데 `30.832`초에 눌렀다면 0.2초 뒤에 4:59로 변하게 됩니다
결과적으로 5:00에서 곧바로 4:59로 바뀌게 되어 마치 에러처럼 보이더라고요
차라리 59에서 천천히 58로 내려가는 게 더 낫다고 판단해서 -1을 해줬습니다
isActive이면 전송 버튼을 클릭한 시간과 5분이 지난 시간을 갖도록 하였습니다
```tsx
const initialDate = new Date(); …
```
> [Fix] 페이지 벗어나 있으면 타이머 안 움직이는 에러 해결

- src/views/ResultPage/index.tsx
**Related Issue :** Closes #314 
---
> [Fix] 지원 안했으면 결과 페이지 막기

- src/views/ApplyPage/components/FileInput/index.tsx
**Related Issue :** Closes #319 
---
파일을 업로드 하는 동안 새로운 파일을 입력 못하도록 disabled 처리 했습니다
> [Fix] 파일 업로드 하는 동안 새로운 파일 업로드 못하도록 막기

- package.json
- src/App.tsx
- src/common/components/Checkbox/index.tsx
- src/common/components/Select/index.tsx
- src/common/components/Textarea/components/Input/index.tsx
- src/views/ApplyPage/components/DefaultSection/index.tsx
- src/views/ApplyPage/components/FileInput/index.tsx
- src/views/dialogs/SubmitDialog/index.tsx
- yarn.lock
**Related Issue :** Closes #331 
---
일단 저희는 amplitude 사용을 위한 SDK(@amplitude/analytics-browser)를 사용하고 있었어서
session replay 또한 SDK(@amplitude/plugin-session-replay-browser)를 사용하는 방향으로 갔습니다
공식문서에서 그렇게 하는 걸 추천하더라고요
> This article covers the installation of Session Replay using the Browser SDK plugin. If your site is already instrumented with Amplitude, use this option.
[참고자료](https://amplitude.com/docs/session-replay/session-replay-plugin#)
session replay를 위한 코드는 굉장히 간단했어요
```tsx
const sessionReplayTracking = sessionReplayPlugin({
sampleRate: 0.7,
});
add(sessionReplayTracking);
```
`sampleRate`는 세션의 저장 비율인데요
100개의 세션이 발생된다면 그 중 70개만 랜덤으로 저장시킨다는 얘기죠!
저희는 무료 버전이라 1,000개의 session replay를 할 수 있는데요
그래서 약 1,428개 정도의 세션만 감당이 가능해요
공식문서에선 0.01로 설정한 후 상황을 지켜보며 천천히 올리라고 하는데 …
> [Feat] amplitude session replay 추가

- src/views/ApplyPage/components/FileInput/index.tsx
**Related Issue :** Closes #333 
---
pptx, pdf 에서 pdf 로 제출 형식 제한을 수정합니다. 
디자인 측에서는 placeholder 라이팅을 바꿔달라고 요청하였지만, 
그 뜻은 결국 사용자가 pdf만 제출하길 바란다는 의미이므로 제출 accept 형식 자체를 pdf만 받도록 구정하였습니다
> [Fix] 포트폴리오 파일 형식 제한

- src/views/ApplyPage/components/FileInput/style.css.ts
- src/views/ApplyPage/components/Info/index.tsx
**Related Issue :** Closes #338 
---
생각보다 에러 많아서 모집 끝나고 이전 pr은 draft 해둔 상태고,
모집 기간 이후 수정해야 할 거 같아여
그래서 일단 이것들만 수정했습니다!!
코리 남겨주신 것들은 저짝 branch에서 계속 진행해 볼게여!
> [Fix] 파일 관련 필수 에러만 제거

- src/views/CompletePage/apis.ts
- src/views/CompletePage/components/Survey.tsx
- src/views/CompletePage/hooks/useMutateSatisfaction.ts
- src/views/CompletePage/index.tsx
- src/views/CompletePage/style.css.ts
- src/views/CompletePage/types.ts
- src/views/SignedInPage/index.tsx
**Related Issue :** Closes #341 
---
Complete Page에 사용자 만족도 조사를 추가합니다 
https://github.com/user-attachments/assets/326fa28b-bb1b-42c7-9452-d864caa80924
- 만족도 조사 추가되면서 레이아웃 전반적으로 좁아져서 수정사항 반영했어요
**🚀 조건부 렌더링되는 컴포넌트에 애니메이션 넣기** 
일반적으로 조건부 렌더링은 JSX에서 조건부로 다른 컴포넌트 리턴시켜주는 식으로 구현되는데요, 
이번에 `점수선택부분` 과 `소중한의견감사드려요` 텍스트는 transition 효과가 들어가야 했어요. 
근데 일반적인 방법대로 조건부렌더링 해주면 fade-out 애니메이션이 보여지기도 전에 컴포넌트가 언마운트 돼서 애니메이션 효과가 적용이 안됩니다. (아마 언석님도 겪어보셨을 이슈일거예요) 
따라서 
- 두 컴포넌트를 감싸는 div를 하나더 만들어서 `position: relative`를 주고 
- 각 컴포넌트에 `position: absolute` 를 줘서 위치를 겹쳐준 다음 
- styleVariant를 통해 **opacity 값을 조건부 스타일링** 해주었습니다. 
이런 케이스에, 언석님이 사용하시는 다른 해결책이 있다면 그것도 궁금해요!! 검색해봐도 다 별로 내키지 않더라구요.. 
> 참고로 큰 역할 안하는 태그에는 그냥 인라인 스타일링 해주었는데, 혹시 인라인 스타일 모두 스타일파일에 분리시켜주길 원하시면 말씀해주세요!! 반영하겠습니다 
**🚀 텍스트 세로 정렬 대체 어떻게 해결하시나요** 
텍스트 세로 …
> [Feat] CompletePage 사용자 만족도 조사 추가 

- src/views/SignedInPage/index.tsx
- src/views/SignupPage/hooks/useMutateSignUp.tsx
**Related Issue :** Closes #344 
---
tanstack query의 onSuccess 이용해줬어요
sign-up 버튼 클릭 -> click-signup-apply
sign-up 완료 -> done-signup-apply
지원서 최종 제출 버튼 클릭 -> click-apply-confirm_submit
지원서 최종 제출 완료 -> done-apply-confirm_submit
> [Feat] amplitude 허수 판독기

- src/views/email/complete.html
**Related Issue :** Closes #330 
---
본 메일 ~ 그부분 중앙정렬이 되지 않아서 해결해주었습니다! 
(as-is)
로고 이미지 관련은 네트워크 이슈인 것으로 추측돼서 
우선 하단 메시지 중앙 정렬만 개선해두었습니다! 
인증 메일 PR에서 설명드렸던 레거시 attributes가 안먹는 이슈였어서 
얘네들도 마저 inline style로 바꿔주었습니다~~
> [Fix] 지원 완료 이메일 템플릿 깨짐 해결 

- src/common/components/Input/components/InputButton/style.css.ts
**Related Issue :** Closes #349 
---
window가 없어서 테스트는 못 해봤어요
하지만 건영님이 테스트 해본 방식을 적용했기에 잘 작동할 것으로 판단이 됩니다
이메일 확인버튼과 인증 확인 버튼은 공통 컴포넌트를 공유하고 있는데
인증 확인 버튼의 크기가 이메일 확인 버튼의 크기와 일치해야 했어요
그렇기에 width를 고정적으로 박아야 해서 width: max-content는 이용할 수가 없었어요
대신 두 번째 추천 방법인 padding을 줄이는 방법을 택했습니다
사파리와 크롬, arc, firefox에서 문제 없는 거 확인했습니다!
> [Fix] 이메일 인증 버튼 크기 깨지는 에러 해결

- src/views/ApplyPage/components/ApplyInfo/index.tsx
**Related Issue :** Closes #355 
---
date-fns format에 분단위(mm)도 추가했어요! 
시간 다루는건 웬만하면 분까지 구체적으로 보여주는게 좋을 것 같아서 
서류 발표에도 분 추가했습니다!
**어푸 해주시면 머지 후에 develop한번 main으로 merge 시킬게요!**
> [Fix] 분 단위 추가

- src/common/hooks/useScrollPosition.tsx
- src/views/ApplyPage/components/ApplyCategory/index.tsx
- src/views/ApplyPage/components/ApplyCategory/style.css.ts
- src/views/ApplyPage/components/CommonSection/style.css.ts
- src/views/ApplyPage/components/PartSection/style.css.ts
- src/views/ApplyPage/style.css.ts
**Related Issue :** Closes #345 
---
https://github.com/user-attachments/assets/209eb4cc-9944-4e26-973a-9f2e6e8d159e
공홈 거 가져왔어요!
다만 조금 더 확장을 했는데요
기존에는 상단 페이지인 경우 스크롤의 상관 없이 항상 보여지도록 구현을 했어요
이때 상단 페이지인지 구분하기 위해 window.scrollY이 20보다 작은지를 기준으로 삼고 있었어요
하지만 저희는 category가 header랑 딱 붙기 전까진 계속 보여져야 했으므로 window.scrollY이 950보다 작아야 했어요
그래서 이를 동적으로 설정할 수 있도록 해줬어요
기본값은 20입니다
```tsx
const useScrollPosition = (topYScrollPosition: number = 20) => {
// ...
useEffect(() => {
const scrollHandler = () => {
const currentScrollPosition = window.scrollY;
setIsScrollTop(currentScrollPosition < topYScrollPosition);
// ...
```
gap을 100으로 늘려줬어요
왜냐면 category 클릭 시 아래 사진과 같이 윗 부분 section도 살짝 보이게 되더라고요
대신 section의 padding top을 줄여주어 디자인적으로는 변함이 없도록 했어요
> [Feat] 헤더 스크롤 시 숨김 처리

- src/views/ApplyPage/components/ApplyInfo/index.tsx
**Related Issue :** Closes #359 
---
admin에 마감 시간을 00:00로 입력하게 하고
화면에 보여지는 건 거기서 1분 뺀 23:59이 보여지도록 했어요
(아직 admin 수정 안해서 23:58로 보입니다)
코드 딴에서 00시로 설정하면 59분으로 설정합니다
> [Fix] 23:59에 지원서 마감되는 에러 해결

- src/views/ApplyPage/components/ApplyCategory/index.tsx
- src/views/ApplyPage/components/ApplyCategory/style.css.ts
- src/views/ApplyPage/index.tsx
- src/views/ReviewPage/index.tsx
**Related Issue :** Closes #361 
---
https://github.com/user-attachments/assets/909178af-41bb-4c88-9fb5-b42ce8bed040
원래는 scrollY가 950 이상이 되어야 사라지도록 설정이 되어 있었는데
리뷰 페이지는 apply info가 지원서 페이지보다 양이 작아
380 정도에 사라지도록 설정했습니다
> [Fix] apply page 카테고리 관련 에러 해결

- package.json
- src/views/ApplyPage/components/DefaultSection/index.tsx
- src/views/ApplyPage/index.tsx
- yarn.lock
**Related Issue :** Closes #365 
---
사용자가 정상적으로 사진을 제출했으나, 서버에 undefined로 저장되고 사진이 제출이 안되었던 이슈 
-> input file `첨부 취소` 처리가 되어있지 않아 발생한 문제 
> 문제 상황
https://github.com/user-attachments/assets/3a0b4c62-56cc-478c-a556-3ab979d3a7eb
> 해결 완료 
https://github.com/user-attachments/assets/b02fb8e1-9bd3-4f6c-b5d2-0eef69b8bbd7
⚠️ **form value update와 관련된 문제라고 추측되어서 디버깅을 위해 `react-hook-form의 devTool` 의존성을 추가로 설치하였습니다!** 
> pull 받으신 후 yarn 한번 해주세요 
> 우선 모든 페이지에서 사용하진 않고, ApplyPage에만 적용시켜주었습니다. 추후 필요에 따라 다른 페이지에도 넣어주면 될 것 같아요 
원인 파악은 오래걸렸으나, 사실 해결 코드는 몇줄 되지 않습니다! 
주요 원인은 
**사용자가 사진을 첨부했다가, 다시 첨부하기를 누른 후 이를 취소**했을 경우, 
form value 값은 undefined로 초기화가 되지만, 
지원서 상의 이미지 미리보기와, form validation을 위한 required 조건에서는 별도의 image state를 사용해주고 있어서 
두 데이터 사이의 싱크가 맞지 않아 발생한 문제였습니다! 
사용자가 첨부 취소를 할 경우, 이전에 첨부한 이미지를 form …
> [Fix] 프로필 사진 undefined로 서버에 전송되는 이슈 해결

- src/common/components/Checkbox/index.tsx
- src/views/ApplyPage/index.tsx
**Related Issue :** Closes #367 
---
https://github.com/user-attachments/assets/01ac0f02-9f73-4424-9b50-7bc4ecf3fe26
같은 useEffect 안에 사진 에러 로직과 체크박스 에러 로직을 넣어놔서
체크박스 에러가 변경이 될 때 사진 에러에 대한 로직이 적용되어서 그랬던 거 였습니다
일단 둘을 분리함으로써 해결해줄 수 있었어요
사진 같은 경우 input을 안 보이게 설정하고 div와 label 태그를 이용해서 사진을 렌더링 해주고 있는데요
이 때문에 최종 제출 버튼 클릭 시 빈칸임에도 불구하고 자동 focus가 되지 않더라고요 (setFocus도 안 되어요ㅜ)
체크박스가 현재 화면에 보이지 않을 때 자동 포커스가 되는데 아래 사진처럼 헤더에 가려져있을 때는 안 되더라고요
아마 현재 화면에 표시되고 있는데 헤더에 가려져서 안 보이는 것처럼 보일 뿐이라 그런 거 같아요
위와 같은 이유로 navigate를 써주기로 했어요
```tsx
if (
(Object.keys(errors).length === 2 && errors.attendance && errors.personalInformation) ||
(Object.keys(errors).length === 1 && (errors.attendance || errors.personalInformation))
)
```
체크박스가 포커스 되어야 할 경우는 오로지 체크박스에만 에러가 발생했을 경우예요
그 외의 경우는 모두 다른 에러 쪽으로 포커스가 가야 하거든요
그래서 위와 같이 길게 …
> [Fix] 사진과 체크박스의 필수 여부 체크할 때 발생되는 에러 해결

- src/views/MyPage/index.tsx
- src/views/MyPage/style.css.ts
- src/views/SignedInPage/index.tsx
**Related Issue :** Closes #372 
---
반응형 마이페이지를 구현했습니다 
> 반응형 
https://github.com/user-attachments/assets/3e9d6731-8cc7-40c8-9aaf-9ac0b0fcea25
> 모바일, 작은창 접속 막기 
https://github.com/user-attachments/assets/13dce1fd-6ccd-4c53-a808-01ca4471fcc7
https://github.com/user-attachments/assets/de4fc89a-efe4-43ae-97b9-b11a549ca601
🚀 **마이페이지 반응형 작업** 
다 styleVary만 쳐주면 되는거라 무리없이 작업했습니다 
([반응형 요소들 정리한 노션](https://lydiacho.notion.site/MAKERS-mob-0823bc9402ee47f5a24cc6af3768e993?pvs=4))
🚀 **ReviewPage 접속 제한** 
전에 이야기했던 대로 ReviewPage는 우선 반응형 작업 미루고, 따라서 `지원서 확인` 클릭 시 사용자 상태를 체크해서 접속 제한 처리를 해줬는데요, 
두가지 케이스가 있어요 
- 모바일로 접속 : userAgent를 통해 사용자 디바이스 환경을 체크
- 작은 창으로 접속 : useDevice 훅 사용해서 창 크기가 768이하인지 체크 
이때 모바일로 접속하면 무조건 'PC로 접속하라'는 alert 띄우고 **이동을 막으면** 되는데, 
PC에서 작은 창으로 접속할 경우에도 PC로 접속하라는 alert을 띄우는게 부적절하다고 …
> [Design] Mobile ver. - MyPage 구현

- src/views/ApplyPage/index.tsx
- src/views/dialogs/PreventApplyDialog/index.tsx
**Related Issue :** Closes #383 
---
NoMoreApply가 true가 되면 제출이 불가능하도록 설정했어요~
제출 버튼 혹은 임시저장 클릭 시 모달창 뜨도록 설정했어요~
> [Fix] 제출 기한 지나면 제출 못하도록 막기

- src/views/CompletePage/style.css.ts
- src/views/ErrorPage/components/ErrorCode/index.tsx
- src/views/ErrorPage/components/ErrorCode/style.css.ts
- src/views/ErrorPage/components/NoMore/index.tsx
- src/views/ErrorPage/index.tsx
- src/views/ErrorPage/style.css.ts
- src/views/loadings/BigLoding/style.css.ts
**Related Issue :** Closes #378 
---
단순 작업이라 크게 어려움은 없었어요
header를 sticky에서 fixed로 변경하면서 padding을 80 추가 해준 덕분에 
에러 페이지에서 헤더가 있는지 없는지에 따라 조건부로 height을 계산할 필요가 없어졌어요
헤더 있든 없든 padding 80은 항상 존재하니까요
다만 기존에는 74로 설정이 되어있었기에 이를 다 80으로 수정했어요
no more page는 제가 만든 페이지라 디자인이 없어요 😅
해당 페이지 만들 때 error page를 참고하여 만든 거기 때문에 에러 페이지와 동일하게 적용해줬어요
> [Design] Mobile ver. - ErrorPage 구현

- src/common/hooks/useDevice.ts
**Related Issue :** Closes #390 
---
- breakPoint가 428/429 에서 430/431 로 바뀌어서 반영해줬어요 
- useDevice에 breakPoint 주입할 수 있도록 prop 뚫어줬어요 
Footer 같은 경우, 특수하게 breakPoint 가 혼자 달라요. 
이런 케이스가 앞으로도 생길 수 있기 때문에 tablet breakPoint, mobile breakPoint 주입해줄 수 있도록, 
대신 기존에 사용된 훅들에 영향 없도록 optional prop 추가해주었습니다
> [Fix] useDevice hook 확장 

- src/common/components/Select/index.tsx
- src/common/components/Textarea/components/Input/index.tsx
- src/common/hooks/useDevice.ts
- src/views/ApplyPage/components/FileInput/index.tsx
- src/views/MyPage/index.tsx
- src/views/ResultPage/components/FinalResult.tsx
- src/views/ResultPage/components/ScreeningResult.tsx
**Related Issue :** Closes #395 
---
기존에는 뚫어놨었던 지원자 답변과 파트 선택 여부를 다시 masking 처리 했어요
<br />
마이 페이지에서 기수, 이름, 지원 파트, 합불 여부에 대한 정보를 마스킹 처리 했어요
<br />
합격 페이지에서 구글폼 클릭 시 이벤트가 트래킹 되도록 구현했어요
이벤트 이름은 `click-final-google_form` / `click-screening-google_form` 으로 해줬습니다
<br />
> [Feat] session replay masking 추가

- src/App.tsx
- src/common/components/Dialog/index.tsx
- src/common/components/Dialog/style.css.ts
- src/views/ApplyPage/index.tsx
- src/views/ReviewPage/index.tsx
- src/views/SignupPage/components/SignupForm/index.tsx
- src/views/dialogs/CompleteDialog/index.tsx
- src/views/dialogs/DraftDialog/index.tsx
- src/views/dialogs/ExistingApplicantDialog/index.tsx
- src/views/dialogs/ExitDialog/index.tsx
- src/views/dialogs/PreventApplyDialog/index.tsx
- src/views/dialogs/PreventReviewDialog/index.tsx
- src/views/dialogs/SessionExpiredDialog/index.tsx
- src/views/dialogs/SubmitDialog/index.tsx
- src/views/dialogs/SubmitDialog/style.css.ts
- src/views/dialogs/index.tsx
- src/views/dialogs/style.css.ts
**Related Issue :** Closes #377 
---
몇 개는 해당 컴포넌트에서 import 되고 있어서
기존 방식인 index.tsx에서 한 번에 import 해주는 방식으로 통일했어요
```tsx
export { default as CompleteDialog } from './CompleteDialog';
export { default as DraftDialog } from './DraftDialog';
export { default as ExistingApplicantDialog } from './ExistingApplicantDialog';
export { default as ExitDialog } from './ExitDialog';
export { default as PreventApplyDialog } from './PreventApplyDialog';
export { default as PreventReviewDialog } from './PreventReviewDialog';
export { default as SessionExpiredDialog } from './SessionExpiredDialog';
export { default as SubmitDialog } from './SubmitDialog';
```
> [Design] Mobile ver. - Dialog 구현

- index.html
- src/common/components/Layout/index.tsx
**Related Issue :** Closes #402 
---
메타태그에 && 연산자 사용해서 저번처럼 `false` 가 들어가서, 삼항연산자로 바꿔주었어요 ! 
(이런 문제였음!)
> [Fix] meta tag && 연산자 삭제

- src/common/components/Checkbox/index.tsx
- src/common/components/Checkbox/style.css.ts
- src/common/components/Radio/components/Option/style.css.ts
- src/views/ApplyPage/components/BottomSection/index.tsx
**Related Issue :** Closes #381 
---
ReviewPage에서 click 및 hover 비활성화 처리가 누락되어있는 부분들이 있어서 마저 처리해주었습니다. 
- Radio
https://github.com/user-attachments/assets/adb10731-b6e3-4440-ac7e-65c28b1aa870
- CheckBox
https://github.com/user-attachments/assets/1547c0c5-d3fb-4bc2-a033-9accea0a46ef
> 동적 metatag pre-render 이슈는 생각보다 더 오래 걸릴 것 같아서 중간에 멈추고 자잘한 버그픽스부터 하려고 해요! ㅠㅠ
cursor도 not-allowed로 바꿔주고, hover 했을 때 색 달라지는 것도 disabled의 느낌을 방해한다고 생각해서 hover 조건에 enabled (disabled 아닐 때) 도 추가해주었어요!
> [Fix] ReviewPage 클릭 비활성화 처리 

- src/views/MyPage/index.tsx
**Related Issue :** Closes #408 
---
다시보기도 이제 반응형 지원하니까 해당 alert는 없어도 될 거 같아 제거했어요!
App.tsx에 mobile 관련 regex가 주석으로 남아있어서
MyPage에는 해당 코드 제거해줬어요!
> [Fix] 전체화면 권장 제거

- src/common/components/Checkbox/index.tsx
**Related Issue :** Closes #415 
---
만약 `<Checkbox>`이런 식으로 컴포넌트에 disabled 속성이 없어도
```tsx
<input
{...register(name, {
...(required && { required: '필수 동의 항목이에요.' }),
onChange: () => trigger(name),
})}
type="checkbox"
className={`amp-unmask ${hiddenCheckbox}`}
disabled
{...checkboxElementProps}
/>
```
Checkbox 내의 input에 disabled가 설정되어 있어 체크가 막혀버려요
disabled 속성을 추가할 경우
{...checkboxElementProps}에 자동으로 disabled도 포함되기에 지워줬습니다
반대로 `<Checkbox>` 이렇게만 입력 시 disabled 속성이 없기에 disabled 처리가 되지 않게 돼요
분명 해당 이슈 코리할 때 잡을 수 있었을 텐데 아쉬워요ㅜ
다음부턴 좀 더 신경써서 꼼꼼하게 코리하도록 하겠습니다ㅜㅜ😢
> [Fix] 체크박스 선택 안 되는 에러 해결

- index.html
**Related Issue :** Closes #418 
---
- index.html 하드코딩 수정 과정에서 manifest 파일명을 잘못써서 수정했습니다 
- og tag Link를 full url로 수정해주었습니다. 
현재 위와 같이 다른 Og는 잘 뜨는데, 이미지만 안뜨고 있는걸 확인할 수 있어요. 
og의 경우 public 폴더 하의 에셋들을 사용할 때, 경로를 작성하면 안되고 도메인까지 붙인 full url을 넣어줘야 정상작동합니다. 
따라서 url로 고쳐주었어요! 
배포해서 확인해보고 잘 되면 SOPT 레포에도 반영할 예정입니다
> [Fix] manifest 및 og tag link 수정

- src/views/CompletePage/components/Survey.tsx
- src/views/SignedInPage/index.tsx
**Related Issue :** Closes #426 
---
만족도 조사 여러번 제출 -> 한번만 제출하도록 허용 
https://github.com/user-attachments/assets/eb343012-2647-4fa1-a5e0-ffde2e06c0d3
2.2초 후에 다시 선택지 띄우는 타이머 삭제해주었습니다
> [Fix] 만족도 조사 제출 1회만 허용 

- src/common/components/Input/components/InputLine/index.tsx
- src/common/components/Input/components/InputLine/style.css.ts
**Related Issue :** Closes #427 
---
16px 미만으로 설정되어있는 input 때문에 iOS safari에서 입력창 focus 시 자동으로 zoom이 되는 이슈 해결 
- 14px
https://github.com/user-attachments/assets/bb0fa021-d051-4d8e-ad9a-777031ac7c88
- 16px
https://github.com/user-attachments/assets/83a98c27-0ebc-4d2f-ad18-7bb000a13529
meta tag viewport에서 user-scalable 설정을 해줘서 막는 방법도 있지만, 
이는 접근성을 위한 기능을 강제로 막는 방식이기 때문에 최대한 지양하는 것이 좋다고 판단했습니다 
따라서 디자이너분들께 이슈 공유하고 14px이었던 모바일뷰 폰트 사이즈를 16px로 수정 (다른 뷰와 통일) 하는 것으로 수정했습니다 ~~
> [Fix] 텍스트필드 모바일뷰 폰트 사이즈 14->16px 수정 

- src/common/apis/tokenInstance.ts
- src/common/components/Input/components/Timer/index.tsx
- src/common/hooks/useDate.tsx
- src/views/ApplyPage/components/ApplyInfo/index.tsx
- src/views/ResultPage/components/FinalResult.tsx
- src/views/ResultPage/components/ScreeningResult.tsx
**Related Issue :** Closes #431 
---
개선된 건 [PR 3](https://github.com/sopt-makers/sopt-recruiting-frontend/pull/432)에서 확인할 수 있어요
필요 없는 부분들 까지 같이 import 되고 있더라고요?
예를 들어 ko가 아닌 다른 나라 locale 등등
정말 필요한 부분만 import 되도록 범위 수정해 줬어요
사실 그렇다할 유의미한 차이(0.01kb 감소)는 없었는데요 build 시간을 조금 단축(0.5s 단축)할 수 있었어요
> [Refactor] 번들 크기 개선 - 2

- src/App.tsx
- src/views/ApplyPage/index.tsx
- src/views/MyPage/index.tsx
- src/views/PasswordPage/components/PasswordForm/index.tsx
- src/views/PasswordPage/index.tsx
- src/views/ResultPage/index.tsx
- src/views/ReviewPage/index.tsx
- src/views/SignInPage/index.tsx
- src/views/SignupPage/components/SignupForm/index.tsx
- src/views/SignupPage/index.tsx
- vite.config.ts
**Related Issue :** Closes #431 
---
전
후 (번들 크기 개선 1, 2, 3이 통합된 결과예요)
build 속도를 6.11s 에서 4.99s로 1s 정도 개선할 수 있었습니다 :)
경고창에 manual chunk를 이용하라고 추천해줘서 바로 적용해줬어요
모든 chunk를 로드할 필요 없이 필요한 chunk만 필요한 곳에서 사용하자는 개념이에요
firebase는 지원서 페이지의 파일 input에서만 사용되기에 다른 페이지에선 쓸 일이 없어요
그래서 firebase를 별도의 chunk로 분리해줬답니다
manual chunk와 비슷한 개념인데요 잘 아실거라고 생각들어요
dialog와 error page, nomore page는 특정 상황에서만 필요하기에 첫 페이지 로딩 때는 필요가 없어요
그래서 lazy loading 적용 시켜줬어요
추가로 하나의 페이지에 접속했을 때 다른 페이지는 필요하지 않으므로
router에서 각 페이지에 대한 lazy loading도 적용시켜줬어요
> [Refactor] 번들 크기 개선 - 3

- src/common/apis/getRecruitingInfo.ts
- src/common/apis/instance.ts
- src/common/components/Input/apis.ts
- src/views/PasswordPage/apis.ts
- src/views/SignInPage/apis.ts
- src/views/SignupPage/apis.ts
**Related Issue :** Closes #444 
---
코드 짜기 전에는 hook으로 분리해줄까 했었는데
짜고 보니 분리할 필요가 없더라고요?
원래 방식처럼 그냥 바로 instance 가져다가 사용하면 됐어요
사용법은 비슷해요
첫 번째 인자로 url 넣어주고 두 번째 인자로 options들 넣어주면 됩니다~
단 body는 JSON.stringify()로 감싸줘야 해요!
```tsx
const api요청 = async (인자들) => {
const res = await fetchInstance(url, {
method: 'POST',
headers: {
// ...
},
body: JSON.stringify({
// ...
}),
// ...
});
return res;
};
```
> [Refactor] token 필요없는 fetch custom hook 만들기

- src/App.tsx
- src/common/hooks/useDialog.tsx
- src/common/hooks/useEventListener.tsx
- src/views/ApplyPage/components/ApplyCategory/index.tsx
- src/views/ApplyPage/components/ApplyHeader/index.tsx
- src/views/ApplyPage/components/ApplyInfo/index.tsx
- src/views/ApplyPage/components/BottomSection/index.tsx
- src/views/ApplyPage/components/CommonSection/index.tsx
- src/views/ApplyPage/components/DefaultSection/index.tsx
- src/views/ApplyPage/components/PartSection/index.tsx
- src/views/ApplyPage/hooks/useBeforeExitPageAlert.tsx
- src/views/ApplyPage/index.tsx
- src/views/PasswordPage/components/PasswordForm/index.tsx
- src/views/ReviewPage/index.tsx
- src/views/SignupPage/components/SignupForm/index.tsx
**Related Issue :** #440 
---
apply page 내에서
관심사 분리하려고 따로 분리해줬습니다 :)
dialog 관련 함수들이 모여있는 hook을 생성해줬어요
분리하는 김에 다른 페이지에 있는 dialog들도 다 분리해줬습니다 :)
변하지 않는 변수라 component 내에 있을 필요가 없어 보였어요
외부로 빼줬습니다
<App />에 Suspense로 fallback을 제공하고 있어서 제거해 줬습니다 :)
> [Refactor] ApplyPage 로직 분리 - 1

- src/common/apis/fetcher.ts
- src/common/apis/getRecruitingInfo.ts
- src/common/apis/instance.ts
- src/common/components/Input/apis.ts
- src/common/components/Input/hooks/useMutateCheckCode.tsx
- src/common/components/Input/hooks/useMutateCheckUser.tsx
- src/common/components/Input/hooks/useMutateSendCode.tsx
- src/common/hooks/useDate.tsx
- src/common/hooks/useGetRecruitingInfo.tsx
- src/views/PasswordPage/apis.ts
- src/views/PasswordPage/hooks/useMutateChangePassword.tsx
- src/views/SignInPage/apis.ts
- src/views/SignInPage/hooks/useMutateSignIn.tsx
- src/views/SignupPage/apis.ts
- src/views/SignupPage/hooks/useMutateSignUp.tsx
**Related Issue :** Closes  #449 
---
가능한 에러 경우의 수 다 테스트 완료했어요 물론 정상 플로우도 다 테스트 했습니다
비번 틀림
존재하는 계정
이미 가입된 계정
비번 찾기 - 존재하지 않는 계정
인증번호 실패
fetch는 axios와 달리 4xx, 500 에러가 나도 error를 throw 하지 않고 response에 그냥 반환을 해요
그래서 에러가 발생 시 따로 error를 throw 해야 했어요
이때 error status를 같이 넘겨줌으로써 에러 로직을 세분화 시킬 수 있게 했어요
이때 기존 Error에는 status가 없어서 type 에러가 나기에 status가 추가된 CustomError class를 생성해줬어요
[관련커밋](https://github.com/sopt-makers/sopt-recruiting-frontend/commit/4eac3f9622731637b730bf015ac6356015577fd2)
GET으로 data 보낼 때 params에 담아서 보내줘야 하는데 이를 위해 URLSearchParams를 이용하여 url 뒤에 붙여줬어요
그 외에는 body에 data를 보내줘야 하는데 이때 JSON.stringfy로 감싸줘야 해요
매번 해주기 귀찮아서 instance에 처리해줬어요
[관련커밋](https://github.com/sopt-makers/sopt-recruiting-frontend/commit/909485054d09ad3b51e6d62a35e985733a649111)
form data를 보낼 때는 application/json 타입이 아니라서 …
> [Refactor] fetch instance 기능 보강

- src/common/hooks/useCheckBrowser.ts
**Related Issue :** Closes #423 
---
https://github.com/user-attachments/assets/45e59672-57dc-45fb-95d4-08faa60be348
https://github.com/user-attachments/assets/92b91430-5fa5-474a-ad17-5c9c859d22f4
[ua-parser-js의 방식](https://github.com/faisalman/ua-parser-js/blob/master/src/main/ua-parser.js)을 참고했어요
> [Fix] 모바일 크롬 접속 시 크롬으로 접속 권하는 alert 뜨는 에러 해결

- src/views/ResultPage/components/ScreeningResult.tsx
서류 결과 확인 페이지에서 일정을 조회할 때, 
```recruiting-season/latest``` ⇒ 해당 API 로 기수의 전체적인 일정을 가져오고 있었음. 
받아온 interviewStart, interviewEnd 필드를 format 하여 하드코딩 대신 서버에서 조회된 값으로 처리
> [FIX] 서류결과 인터뷰일정 서버에서 받아온 값으로 처리
